on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Validate bangs.json
jobs:
  validate-bangs-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: ScratchAddons/validate-json-action@8f71e0683221310e32661c1b1634399858bde75f
        env:
          schema: ./data/bangs.schema.json
          jsons: |
            ./bangs.json
          separator: '\n'
