on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Validate bangs.json
jobs:
  validate-bangs-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        uses: walbo/validate-json@v1.1.0
        with:
          files: data/*bangs.json

          # optional, defaults to `$schema` in your JSON file
          schema: ./data/bangs.schema.json

          # optional, default: draft-04
          schema-version: draft-07

          # optional, default: false
          print-valid-files: true

          # optional, default: false
          fail-on-missing-schema: true

          # optional, default: true
          strict: true

          # optional, default: false
          allow-matching-properties: false

          # optional, default: true
          allow-union-types: true
  run-rspec-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          ruby-version: 3.0
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true
      - name: Run tests
        run: |
          bundle exec rspec
