on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

name: Validate bangs.json
jobs:
  validate-bangs-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Validate JSON
        uses: OrRosenblatt/validate-json-action@a4773333088b27448e122ccd2992d63383ec2342
        env:
          INPUT_SCHEMA: ./data/bangs.schema.json
          INPUT_JSONS: ./bangs.json
